# Generated by Django 4.2.7 on 2023-12-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('collaborator', 'Collaborator'), ('lender', 'Lender')], max_length=20)),
                ('collaborator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
