# Generated by Django 4.2.7 on 2023-12-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_login_alter_user_password_and_more'),
        ('customers', '0001_initial'),
        ('collaborators', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollaboratorDetails',
            new_name='Collaborators',
        ),
    ]
